# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    php73:
      phpVersion: 7.3
    php74:
      phpVersion: 7.4
    php80:
      phpVersion: 8.0
    php81:
      phpVersion: 8.1
    php82:
      phpVersion: 8.2
    php83:
      phpVersion: 8.3
      executeSonar: true

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: 'composer test:coverage'
  env:
    SILA_PRIVATE_KEY: $(silaPrivateKey)
    SILA_PRIVATE_KEY_INVALID: $(silaPrivateKeyInvalid)
    XDEBUG_MODE: coverage
  displayName: 'composer test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
  displayName: 'Publish test results'
  condition: succeededOrFailed()
