name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3']
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, json, mbstring, gmp, openssl
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-security-blocking

      - name: Run tests
        env:
          XDEBUG_MODE: coverage
        run: composer test:coverage